=== Cuervaa/DAW/Lenguaje de Marcas/S1/Unidad 4/Autoevaluacion/productos.dtd
<!ELEMENT catalogo (producto+)>
<!ELEMENT producto (nombre, marca, precio, contenidoFructosa, apto)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT contenidoFructosa (#PCDATA)>
<!ELEMENT apto (#PCDATA)>

=== Cuervaa/DAW/Lenguaje de Marcas/S1/Unidad 4/Autoevaluacion/productos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE catalogo SYSTEM "productos.dtd"> -->
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="productos.xsd">
<producto>
        <nombre>Galletas sin fructosa</nombre>
        <marca>HealthyFood</marca>
        <precio>2.50</precio>
        <contenidoFructosa>0</contenidoFructosa>
        <apto>si</apto>
    </producto>
    <producto>
        <nombre>Pan especial</nombre>
        <marca>BioPan</marca>
        <precio>3.20</precio>
        <contenidoFructosa>0</contenidoFructosa>
        <apto>si</apto>
    </producto>
    <producto>
        <nombre>Bebida vegetal</nombre>
        <marca>GreenLife</marca>
        <precio>1.80</precio>
        <contenidoFructosa>0.5</contenidoFructosa>
        <apto>no</apto>
    </producto>
</catalogo>
